-- Migration 001: webhook_idempotency table
--
-- Stores one row per (provider, reference) pair so that duplicate webhook
-- deliveries from Flutterwave and Paystack are silently deduplicated and the
-- original response body is replayed to the caller.
--
-- Columns
-- -------
-- id            UUID primary key (generated by the application layer).
-- provider      Webhook source: 'flutterwave' | 'paystack'.
-- reference     Provider-supplied idempotency key:
--                 Flutterwave → data.txRef
--                 Paystack    → data.reference
-- received_at   When the first delivery of this event was accepted (UTC).
-- status        Processing outcome: 'processed' | 'dlq' | 'failed'.
-- response_body The JSON body we returned to the provider on first delivery.
--               Replayed verbatim on every duplicate delivery.
--
-- Indexes
-- -------
-- uq_webhook_idempotency_provider_reference
--   Unique constraint prevents concurrent duplicate inserts via DB-level lock.
--   Application code checks this constraint to implement read-before-write
--   deduplication without a separate SELECT.

CREATE TABLE IF NOT EXISTS webhook_idempotency (
    id            TEXT        NOT NULL,
    provider      TEXT        NOT NULL CHECK (provider IN ('flutterwave', 'paystack')),
    reference     TEXT        NOT NULL,
    received_at   TEXT        NOT NULL,  -- ISO-8601 UTC timestamp
    status        TEXT        NOT NULL CHECK (status IN ('processed', 'dlq', 'failed')),
    response_body TEXT        NOT NULL,  -- JSON string

    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_webhook_idempotency_provider_reference
    ON webhook_idempotency (provider, reference);
